import test from "node:test"; import assert from "node:assert/strict";
process.env.APP_MODE="production";process.env.JIRA_BASE_URL="https://acme.atlassian.net";process.env.JIRA_EMAIL="bot@acme.test";process.env.JIRA_API_TOKEN="secret";process.env.SLACK_BOT_TOKEN="xoxb-test";process.env.SLACK_CHANNEL_IDS="C123";process.env.ROUTE_PAYMENTS_SLACK="C999";process.env.MS_TENANT_ID="tenant";process.env.MS_CLIENT_ID="client";process.env.MS_CLIENT_SECRET="secret";process.env.TEAMS_TEAM_ID="team";process.env.TEAMS_CHANNEL_IDS="channel";process.env.OUTLOOK_SENDER="bot@acme.test";
process.env.CONFLUENCE_BASE_URL="https://acme.atlassian.net";process.env.CONFLUENCE_EMAIL="bot@acme.test";process.env.CONFLUENCE_API_TOKEN="secret";process.env.CONFLUENCE_SPACE_ID="SPACE123";
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"Content-Type":"application/json",...headers}});
test("Jira creates a v3 issue with ADF and idempotency property",async()=>{const calls=[];const {createJiraIssue}=await import("../src/connectors/jira.js");const result=await createJiraIssue({id:"a1",title:"Payment failure",summary:"EU checkout failed",sourceId:"m1",severity:"sev1"},{jira:"PAY"},{fetchImpl:async(url,init)=>{calls.push({url,init});return json({key:"PAY-42"},201)}});assert.equal(result.externalId,"PAY-42");const sent=JSON.parse(calls[0].init.body);assert.equal(sent.fields.description.type,"doc");assert.equal(sent.properties[0].value,"a1");});
test("Slack resolves employee email and posts triage metadata",async()=>{const calls=[];const fetchImpl=async(url,init)=>{calls.push({url,body:JSON.parse(init.body)});if(url.endsWith("conversations.history"))return json({ok:true,messages:[{ts:"1720000000.0001",user:"U1",text:"API is down"},{ts:"1720000001.0001",bot_id:"B1",text:"ignore"}]});if(url.endsWith("users.info"))return json({ok:true,user:{real_name:"Ada",profile:{email:"ada@acme.test"}}});return json({ok:true,ts:"1720000002.0001",message:{}})};const {fetchSlackMessages,postSlackTriage}=await import("../src/connectors/slack.js");const messages=await fetchSlackMessages({fetchImpl});assert.equal(messages[0].employee,"ada@acme.test");const out=await postSlackTriage({id:"a1",team:"payments",severity:"sev1",title:"Outage",summary:"Checkout down",sourceId:"m1"},{slack:"C999"},{fetchImpl});assert.equal(out.externalId,"1720000002.0001");assert.equal(calls.at(-1).body.metadata.event_payload.action_id,"a1");});
test("Graph obtains app token, resolves employee, reads Teams, and sends Outlook mail",async()=>{const calls=[];const fetchImpl=async(url,init={})=>{calls.push({url,init});if(url.includes("oauth2"))return json({access_token:"graph-token",expires_in:3600});if(url.includes("/messages?"))return json({value:[{id:"M1",messageType:"message",createdDateTime:"2026-07-18T10:00:00Z",from:{user:{id:"U1",displayName:"Ada"}},body:{content:"<p>Login is broken</p>"}}]});if(url.includes("/users/U1?"))return json({mail:"ada@acme.test"});return new Response(null,{status:202})};const ms=await import("../src/connectors/microsoft.js");ms.resetTokenCache();const messages=await ms.fetchTeamsMessages({fetchImpl});assert.equal(messages[0].employee,"ada@acme.test");const out=await ms.sendOutlookMail({to:"owner@acme.test",subject:"EOD",body:"Done"},{fetchImpl});assert.equal(out.destination,"owner@acme.test");assert.ok(calls.at(-1).url.endsWith("/users/bot%40acme.test/sendMail"));});
test("HTTP retries a 429 response",async()=>{let attempts=0;const {request}=await import("../src/http.js");const result=await request("https://example.test",{fetchImpl:async()=>++attempts===1?json({error:"rate_limited"},429,{"retry-after":"0"}):json({ok:true}),retries:1});assert.equal(result.data.ok,true);assert.equal(attempts,2)});
test("Confluence creates an approved page using storage format",async()=>{let sent;const {createConfluencePage}=await import("../src/connectors/confluence.js");const result=await createConfluencePage({id:"a1",title:"Incident review",draft:{title:"INC-42 review",sections:[{heading:"Summary",text:"Checkout recovered",items:[]},{heading:"Actions",text:"",items:["Add alerting — Ada — Friday"]}]}},{fetchImpl:async(url,init)=>{sent={url,body:JSON.parse(init.body)};return json({id:"9988",_links:{webui:"/spaces/OPS/pages/9988"}})}});assert.equal(sent.body.spaceId,"SPACE123");assert.match(sent.body.body.value,/Checkout recovered/);assert.equal(result.externalId,"9988");});
