import crypto from "node:crypto"; import { config } from "../config.js"; import { request } from "../http.js";
let cached={token:"",expires:0};
async function token(deps={}) { if(cached.expires>Date.now()+60000)return cached.token; const form=new URLSearchParams({client_id:config.microsoft.clientId,client_secret:config.microsoft.clientSecret,scope:"https://graph.microsoft.com/.default",grant_type:"client_credentials"}); const {data}=await request(`https://login.microsoftonline.com/${encodeURIComponent(config.microsoft.tenantId)}/oauth2/v2.0/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:form,fetchImpl:deps.fetchImpl}); cached={token:data.access_token,expires:Date.now()+Number(data.expires_in)*1000}; return cached.token; }
async function graph(path,options={},deps={}) { const access=deps.accessToken||await token(deps); return request(`https://graph.microsoft.com/v1.0${path}`,{...options,headers:{Authorization:`Bearer ${access}`,"Content-Type":"application/json",...(options.headers||{})},fetchImpl:deps.fetchImpl}); }
const textOnly=html=>String(html||"").replace(/<[^>]+>/g," ").replace(/&nbsp;/g," ").replace(/&amp;/g,"&").replace(/\s+/g," ").trim();
const users=new Map();async function graphUser(id,deps){if(!id)return {email:""};if(users.has(id))return users.get(id);try{const {data}=await graph(`/users/${encodeURIComponent(id)}?$select=mail,userPrincipalName`,{},deps),u={email:data.mail||data.userPrincipalName||""};users.set(id,u);return u}catch{return {email:""}}}
export async function fetchTeamsMessages(deps={}) { const out=[]; for(const channel of config.microsoft.channels){ const path=`/teams/${encodeURIComponent(config.microsoft.teamId)}/channels/${encodeURIComponent(channel)}/messages?$top=50`; const {data}=await graph(path,{},deps); for(const m of data.value||[]) if(m.messageType==="message"&&!m.from?.application){const u=await graphUser(m.from?.user?.id,deps);out.push({id:`teams:${channel}:${m.id}`,source:"teams",channel,author:m.from?.user?.displayName||"unknown",employee:u.email,text:textOnly(m.body?.content),at:m.createdDateTime,raw:{webUrl:m.webUrl,userId:m.from?.user?.id}});} } return out; }
export async function sendOutlookMail({to,subject,body},deps={}) { const recipients=(Array.isArray(to)?to:[to]).filter(Boolean).map(address=>({emailAddress:{address}})); if(!recipients.length)throw new Error("Email action has no recipients"); const path=deps.accessToken?"/me/sendMail":`/users/${encodeURIComponent(config.microsoft.sender)}/sendMail`;await graph(path,{method:"POST",body:JSON.stringify({message:{subject,body:{contentType:"Text",content:body},toRecipients:recipients},saveToSentItems:true})},deps); return {externalId:`mail:${crypto.randomUUID()}`,destination:recipients.map(x=>x.emailAddress.address).join(",")}; }
export async function postTeamsTriage(action,deps={}) { if(!config.microsoft.triageWebhook)throw new Error("TEAMS_TRIAGE_WEBHOOK_URL is not configured"); const {data}=await request(config.microsoft.triageWebhook,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({type:"message",attachments:[{contentType:"application/vnd.microsoft.card.adaptive",contentUrl:null,content:{$schema:"http://adaptivecards.io/schemas/adaptive-card.json",type:"AdaptiveCard",version:"1.4",body:[{type:"TextBlock",weight:"Bolder",size:"Large",text:`${action.severity.toUpperCase()} · ${action.title}`},{type:"TextBlock",wrap:true,text:action.summary||""},{type:"TextBlock",isSubtle:true,wrap:true,text:`OpsPilot action ${action.id}`}]} }]}),fetchImpl:deps.fetchImpl}); return {externalId:`teams:${action.id}`,destination:"Teams triage webhook",response:data}; }
export async function microsoftHealth(deps={}) { await token(deps); return {ok:true,tenant:config.microsoft.tenantId}; }
export function resetTokenCache(){cached={token:"",expires:0};}
