import crypto from "node:crypto"; import { config } from "./config.js"; import { request } from "./http.js";
const pending=new Map(),sessions=new Map();const scopes="openid profile email offline_access User.Read Mail.Send";
const b64url=value=>Buffer.from(value).toString("base64url"),cookies=req=>Object.fromEntries(String(req.headers.cookie||"").split(";").map(x=>x.trim().split(/=(.*)/s)).filter(x=>x[0]));
export const authEnabled=()=>Boolean(config.auth.clientId&&config.auth.clientSecret);
export function beginLogin(){const state=crypto.randomBytes(24).toString("hex"),nonce=crypto.randomBytes(24).toString("hex"),verifier=b64url(crypto.randomBytes(48)),challenge=b64url(crypto.createHash("sha256").update(verifier).digest());pending.set(state,{verifier,nonce,expires:Date.now()+10*60_000});const q=new URLSearchParams({client_id:config.auth.clientId,response_type:"code",redirect_uri:config.auth.redirectUri,response_mode:"query",scope:scopes,state,nonce,code_challenge:challenge,code_challenge_method:"S256",prompt:"select_account"});return `https://login.microsoftonline.com/${encodeURIComponent(config.auth.authority)}/oauth2/v2.0/authorize?${q}`;}
async function token(form){const {data}=await request(`https://login.microsoftonline.com/${encodeURIComponent(config.auth.authority)}/oauth2/v2.0/token`,{method:"POST",headers:{"Content-Type":"application/x-www-form-urlencoded"},body:new URLSearchParams(form),retries:1});if(data.error)throw new Error(data.error_description||data.error);return data;}
export async function completeLogin({code,state}){const flow=pending.get(state);pending.delete(state);if(!flow||flow.expires<Date.now())throw Object.assign(new Error("Login state expired or invalid"),{status:400});const tokens=await token({client_id:config.auth.clientId,client_secret:config.auth.clientSecret,grant_type:"authorization_code",code,redirect_uri:config.auth.redirectUri,code_verifier:flow.verifier,scope:scopes});const {data:user}=await request("https://graph.microsoft.com/v1.0/me?$select=id,displayName,mail,userPrincipalName",{headers:{Authorization:`Bearer ${tokens.access_token}`},retries:1});const email=String(user.mail||user.userPrincipalName||"").toLowerCase();if(!email)throw new Error("Microsoft account did not provide an email address");const sid=crypto.randomBytes(32).toString("hex"),role=config.auth.admins.includes(email)?"admin":config.mode!=="production"||config.auth.approvers.includes(email)?"approver":"employee";sessions.set(sid,{id:user.id,name:user.displayName||email,email,role,accessToken:tokens.access_token,refreshToken:tokens.refresh_token,expires:Date.now()+Number(tokens.expires_in||3600)*1000,sessionExpires:Date.now()+config.auth.sessionHours*3600_000});return sid;}
export function sessionCookie(sid){return `opspilot_session=${sid}; Path=/; HttpOnly; SameSite=Lax; Max-Age=${config.auth.sessionHours*3600}${config.auth.secureCookies?"; Secure":""}`}
export const clearCookie=()=>`opspilot_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0${config.auth.secureCookies?"; Secure":""}`;
export function getSession(req){const sid=cookies(req).opspilot_session,s=sessions.get(sid);if(!s||s.sessionExpires<Date.now()){if(sid)sessions.delete(sid);return null}return {sid,...s};}
export function logout(req){const sid=cookies(req).opspilot_session;if(sid)sessions.delete(sid)}
export async function delegatedToken(session){const current=sessions.get(session.sid);if(!current)throw Object.assign(new Error("Session expired"),{status:401});if(current.expires>Date.now()+60_000)return current.accessToken;if(!current.refreshToken)throw Object.assign(new Error("Microsoft authorization expired; sign in again"),{status:401});const tokens=await token({client_id:config.auth.clientId,client_secret:config.auth.clientSecret,grant_type:"refresh_token",refresh_token:current.refreshToken,redirect_uri:config.auth.redirectUri,scope:scopes});current.accessToken=tokens.access_token;current.refreshToken=tokens.refresh_token||current.refreshToken;current.expires=Date.now()+Number(tokens.expires_in||3600)*1000;return current.accessToken;}
export function publicUser(session){return session?{id:session.id,name:session.name,email:session.email,role:session.role}:null}
export function canApprove(session){return session&&["approver","admin"].includes(session.role)}
export function delegatedApproverSession(){const now=Date.now();for(const [sid,s] of [...sessions.entries()].reverse())if(s.sessionExpires>now&&canApprove(s))return {sid,...s};return null}
