import { config, teamRouting } from "./config.js";
import { createJiraIssue, jiraHealth } from "./connectors/jira.js";
import { fetchSlackMessages, postSlackTriage, slackHealth } from "./connectors/slack.js";
import { fetchTeamsMessages, microsoftHealth, postTeamsTriage, sendOutlookMail } from "./connectors/microsoft.js";
import { confluenceHealth, createConfluencePage } from "./connectors/confluence.js";

export const demoMessages=[{id:"m-1042",source:"teams",channel:"Payments Support",author:"Maya Chen",employee:"maya@acme.test",text:"Checkout is failing with 500s for all EU customers. Started about 10 minutes ago; please investigate urgently.",at:new Date().toISOString()}];
export async function fetchMessages(deps={}) { if(config.mode!=="production")return demoMessages; const jobs=[]; if(config.slack.token&&config.slack.channels.length)jobs.push(fetchSlackMessages(deps)); if(config.microsoft.teamId&&config.microsoft.channels.length)jobs.push(fetchTeamsMessages(deps)); const results=await Promise.allSettled(jobs); const messages=results.flatMap(x=>x.status==="fulfilled"?x.value:[]); const errors=results.filter(x=>x.status==="rejected").map(x=>x.reason.message); if(!messages.length&&errors.length)throw new Error(`All message sources failed: ${errors.join("; ")}`); return messages; }
export async function executeAction(action,deps={}) { const route=teamRouting[action.team]; if(!route)throw new Error(`Unknown team route: ${action.team}`); if(config.mode!=="production")return {externalId:`demo-${action.kind}-${action.id.slice(0,8)}`,destination:action.team}; if(action.kind==="jira")return createJiraIssue(action,route,deps); if(action.kind==="triage"){const jobs=[];if(["slack","both"].includes(config.triageProvider)){if(!route.slack)throw new Error(`No Slack channel configured for ${action.team}`);jobs.push(postSlackTriage(action,route,deps))}if(["teams","both"].includes(config.triageProvider))jobs.push(postTeamsTriage(action,deps));const results=await Promise.all(jobs);return results.length===1?results[0]:{externalId:results.map(x=>x.externalId).join(","),destination:results.map(x=>x.destination).join(" + "),results}} if(action.kind==="email")return sendOutlookMail({to:route.email,subject:`[${action.severity.toUpperCase()}] ${action.title}`,body:`${action.summary||action.title}\n\nSource: ${action.sourceId}\nOpsPilot action: ${action.id}`},deps); if(action.kind==="confluence")return createConfluencePage(action,deps); throw new Error(`Unsupported action: ${action.kind}`); }
export async function connectorHealth(deps={}) { if(config.mode!=="production")return {demo:{ok:true}}; const checks={jira:()=>jiraHealth(deps),confluence:()=>confluenceHealth(deps)};if(config.slack.token)checks.slack=()=>slackHealth(deps);if(config.microsoft.tenantId&&config.microsoft.clientId&&config.microsoft.clientSecret)checks.microsoft=()=>microsoftHealth(deps);else if(config.auth.clientId)checks.microsoftOAuth=async()=>({ok:true,mode:"delegated"});const result={}; await Promise.all(Object.entries(checks).map(async([name,fn])=>{try{result[name]=await fn()}catch(e){result[name]={ok:false,error:e.message}}})); return result; }
