import http from "node:http";import https from "node:https";import { readFile } from "node:fs/promises";import { readFileSync } from "node:fs"; import path from "node:path";
import { config, validateProductionConfig } from "./config.js"; import { connectorHealth } from "./connectors.js"; import { verifySlackSignature } from "./connectors/slack.js"; import { readState } from "./store.js"; import { approveAction, buildDigest, createKnowledgeDraft, processMessages, rejectAction, runIntake, sendDigests, updateKnowledgeDraft } from "./workflow.js"; import { recordEodDelivery, startScheduler } from "./scheduler.js";
import { authEnabled, beginLogin, canApprove, clearCookie, completeLogin, delegatedToken, getSession, logout, publicUser, sessionCookie } from "./auth.js";
import { consentStatus, recordConsent, submitPrivacyRequest } from "./privacy.js";import { inc,log,metrics } from "./monitoring.js";
const types={".html":"text/html;charset=utf-8",".css":"text/css;charset=utf-8",".js":"text/javascript;charset=utf-8",".svg":"image/svg+xml"};
const headers={"X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"no-referrer","Content-Security-Policy":"default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; img-src 'self' data:"};
const send=(res,status,data,type="application/json")=>{res.writeHead(status,{...headers,"Cache-Control":type.includes("text/html")?"no-store":"no-cache","Content-Type":type});res.end(type.includes("json")?JSON.stringify(data):data)};
const rawBody=async req=>{const chunks=[];let size=0;for await(const c of req){size+=c.length;if(size>1_000_000)throw Object.assign(new Error("Request too large"),{status:413});chunks.push(c)}return Buffer.concat(chunks).toString("utf8")};
const authorized=req=>!authEnabled()&&config.mode!=="production"||Boolean(config.adminToken)&&req.headers.authorization===`Bearer ${config.adminToken}`||Boolean(getSession(req));
const demoRuns=new Map(),demoCooldownMs=120000;
export function createServer(){const handler=async(req,res)=>{const began=Date.now();res.on("finish",()=>{inc("opspilot_http_requests_total",{method:req.method,status:res.statusCode});inc("opspilot_http_duration_milliseconds_total",{method:req.method},Date.now()-began)});try{const url=new URL(req.url,`${config.tls.certPath?"https":"http"}://localhost`);
  if(url.pathname==="/metrics"){if(config.monitoring.metricsToken&&req.headers.authorization!==`Bearer ${config.monitoring.metricsToken}`)return send(res,401,{error:"Unauthorized"});return send(res,200,metrics(),"text/plain; version=0.0.4; charset=utf-8");}
  if(url.pathname==="/auth/login"){if(!authEnabled())return send(res,503,{error:"Microsoft login is not configured"});res.writeHead(302,{Location:beginLogin(),...headers});return res.end();}
  if(url.pathname==="/auth/callback"){if(url.searchParams.get("error"))throw Object.assign(new Error(url.searchParams.get("error_description")||"Microsoft login failed"),{status:401});const sid=await completeLogin({code:url.searchParams.get("code"),state:url.searchParams.get("state")});res.writeHead(302,{Location:"/",...headers,"Set-Cookie":sessionCookie(sid)});return res.end();}
  if(url.pathname==="/auth/logout"){logout(req);res.writeHead(302,{Location:"/login.html",...headers,"Set-Cookie":clearCookie()});return res.end();}
  if(url.pathname==="/auth/me")return send(res,getSession(req)?200:401,{user:publicUser(getSession(req))});
  if(url.pathname==="/healthz")return send(res,200,{ok:true});
  if(url.pathname==="/readyz") { const connectors=await connectorHealth(); const ok=Object.values(connectors).every(x=>x.ok); return send(res,ok?200:503,{ok,connectors}); }
  if(url.pathname==="/webhooks/slack"&&req.method==="POST"){const raw=await rawBody(req);if(!verifySlackSignature(raw,req.headers["x-slack-request-timestamp"],req.headers["x-slack-signature"]))return send(res,401,{error:"Invalid signature"});const event=JSON.parse(raw);if(event.type==="url_verification")return send(res,200,{challenge:event.challenge});if(event.event?.type==="message"&&!event.event.bot_id){const e=event.event;await processMessages([{id:`slack:${event.event_id}`,source:"slack",channel:e.channel,author:e.user,employee:e.user,text:e.text||"",at:new Date(Number(e.ts)*1000).toISOString()}]);}return send(res,200,{ok:true});}
  if(url.pathname==="/webhooks/incidents"&&req.method==="POST"){if(!config.webhookSecret||req.headers["x-opspilot-secret"]!==config.webhookSecret)return send(res,401,{error:"Invalid webhook secret"});const event=JSON.parse(await rawBody(req)||"{}"),status=String(event.issue?.fields?.status?.name||event.status||"").toLowerCase();if(!["done","closed","resolved","completed"].includes(status))return send(res,202,{accepted:true,draftCreated:false});const issue=event.issue||{},fields=issue.fields||{},description=typeof fields.description==="string"?fields.description:JSON.stringify(fields.description||"");const draft=await createKnowledgeDraft({title:`Incident review: ${issue.key||event.incidentId||fields.summary||"Incident"}`,content:[`Summary: ${fields.summary||event.summary||""}`,`Status: ${status}`,`Description: ${description}`,`Resolution: ${fields.resolution?.name||event.resolution||"Pending confirmation"}`,`Details: ${event.details||""}`].join("\n"),type:"incident",team:event.team||"support",sourceId:`incident:${issue.key||event.incidentId||"unknown"}`});return send(res,202,{accepted:true,draftCreated:true,actionId:draft.id});}
  if(url.pathname.startsWith("/api/")&&!authorized(req))return send(res,401,{error:"Unauthorized"});
  if(url.pathname==="/api/privacy/consent"&&req.method==="GET"){const session=getSession(req);if(!session)return send(res,401,{error:"Unauthorized"});return send(res,200,await consentStatus(session.email));}
  if(url.pathname==="/api/privacy/consent"&&req.method==="POST"){const session=getSession(req),input=JSON.parse(await rawBody(req)||"{}");if(!session)return send(res,401,{error:"Unauthorized"});const result=await recordConsent(session.email,input,{ip:req.socket.remoteAddress});log("info","privacy_consent_updated",{user:session.email,accepted:result.accepted,policyVersion:result.policyVersion});return send(res,200,result);}
  if(url.pathname==="/api/privacy/request"&&req.method==="POST"){const session=getSession(req),input=JSON.parse(await rawBody(req)||"{}");if(!session)return send(res,401,{error:"Unauthorized"});return send(res,201,await submitPrivacyRequest(session.email,input.type));}
  if(url.pathname==="/api/privacy/export"&&req.method==="GET"){const session=getSession(req),state=await readState();if(!session)return send(res,401,{error:"Unauthorized"});return send(res,200,{user:publicUser(session),consents:(state.consents||[]).filter(x=>x.email===session.email),events:state.events.filter(x=>x.message?.employee===session.email),actions:state.actions.filter(x=>x.approvedBy?.email===session.email||x.sourceId?.includes(session.email))});}
  if(url.pathname==="/api/state"&&req.method==="GET")return send(res,200,{...(await readState()),config:{mode:config.mode,policy:config.actionPolicy,ai:!!config.openaiKey,scheduler:{enabled:config.scheduler.enabled,pollMs:config.scheduler.pollMs,eodHour:config.scheduler.eodHour,timeZone:config.scheduler.timeZone},integrations:{slack:Boolean(config.slack.token),jira:Boolean(config.jira.baseUrl&&config.jira.token),outlook:Boolean(config.auth.clientId||config.microsoft.sender),confluence:Boolean(config.confluence.baseUrl&&config.confluence.token)}},user:publicUser(getSession(req))});
  if(url.pathname==="/api/intake"&&req.method==="POST")return send(res,200,await runIntake());
  if(url.pathname==="/api/demo/intake"&&req.method==="POST"){const session=getSession(req),key=session?.email||req.socket.remoteAddress||"demo",last=demoRuns.get(key)||0,now=Date.now();if(now-last<demoCooldownMs)return send(res,429,{error:"Demo intake can be run once every two minutes",retryAfterSeconds:Math.ceil((demoCooldownMs-(now-last))/1000)});demoRuns.set(key,now);const message={id:`demo:slack:${encodeURIComponent(key)}:${now}`,source:"slack-demo",channel:"payments-support",author:session?.name||"Demo user",employee:session?.email||"demo@opspilot.test",text:"Checkout is failing with 500 errors for all customers. Please investigate urgently, notify stakeholders, and create a Confluence incident page.",at:new Date().toISOString()};const result=await processMessages([message]);log("info","demo_intake_completed",{user:session?.email,newMessages:result.new});return send(res,201,{...result,demo:true});}
  if(url.pathname==="/api/digests"&&req.method==="GET")return send(res,200,await buildDigest());
  if(url.pathname==="/api/digests/send"&&req.method==="POST"){const session=getSession(req);if(!canApprove(session))return send(res,403,{error:"Approver role required"});const accessToken=await delegatedToken(session),sent=(await sendDigests({accessToken})).length;if(sent)await recordEodDelivery();return send(res,200,{sent});}
  if(url.pathname==="/api/meetings/draft"&&req.method==="POST"){const input=JSON.parse(await rawBody(req)||"{}");if(!input.transcript||String(input.transcript).length<20)return send(res,400,{error:"A meeting transcript is required"});return send(res,201,await createKnowledgeDraft({title:input.title,content:input.transcript,type:"meeting",team:input.team||"support",sourceId:input.meetingId?`meeting:${input.meetingId}`:undefined}));}
  if(url.pathname.match(/^\/api\/actions\/[^/]+\/draft$/)&&req.method==="PATCH"){const id=url.pathname.split("/")[3],input=JSON.parse(await rawBody(req)||"{}");return send(res,200,await updateKnowledgeDraft(id,input));}
  if(url.pathname.startsWith("/api/actions/")&&req.method==="POST"){const [,,,id,verb]=url.pathname.split("/"),session=getSession(req);if(verb==="approve"&&session&&!canApprove(session))return send(res,403,{error:"Approver role required"});const accessToken=session?await delegatedToken(session):undefined;return send(res,200,verb==="approve"?await approveAction(id,{actor:publicUser(session),accessToken}):await rejectAction(id));}
  if(url.pathname==="/"&&authEnabled()&&!getSession(req)){res.writeHead(302,{Location:"/login.html",...headers});return res.end()}if(url.pathname==="/"&&authEnabled()&&config.privacy.requireConsent&&!((await consentStatus(getSession(req).email)).active)){res.writeHead(302,{Location:"/privacy.html",...headers});return res.end()}
  const requested=url.pathname==="/"?"index.html":url.pathname.slice(1),root=path.resolve("public"),target=path.resolve(root,requested);if(!target.startsWith(root))return send(res,403,{error:"Forbidden"});return send(res,200,await readFile(target),types[path.extname(target)]||"application/octet-stream");
}catch(e){if(e.code==="ENOENT")return send(res,404,{error:"Not found"});log("error","http_error",{method:req.method,path:req.url?.split("?")[0],status:e.status||500,error:e.message});send(res,e.status||500,{error:e.message})}};return config.tls.certPath?https.createServer({cert:readFileSync(config.tls.certPath),key:readFileSync(config.tls.keyPath)},handler):http.createServer(handler)}
if(process.env.NODE_ENV!=="test"){const errors=validateProductionConfig();if(errors.length){console.error(`Configuration error: ${errors.join("; ")}`);process.exitCode=1}else{createServer().listen(config.port,config.host,()=>{console.log(`OpsPilot running at ${config.tls.certPath?"https":"http"}://localhost:${config.port}`);startScheduler()})}}
